### ISSUE TITLE
Transfer file png / jpg do not work. 

### ISSUE THREAD

**Issue by SUPRVISOR** [jitsi/jitsi#435]
Hi, 

The trasnfert file bmp, doc, zip etc is ok
for the png and jpg : ko (nothing is happening)

if i rename the jpg file to bmp or whatever it works

I do not understand where it can come from because with another client on the same server it works.
Win / mac / linux Version stable : 2.10.5550

Best regards.

**Comment by SUPRVISOR** [comment]
nobody, this forum is not very reactive :(

**Comment by GNUDimarik** [comment]
@SUPRVISOR please provide example file and steps to reproduce

**Comment by SUPRVISOR** [comment]
a file BMP for example.
not add BMP here is refused

**Comment by GNUDimarik** [comment]
Thanks for answer!
But @SUPRVISOR  I didn't get you.
Please provide exact steps for reproduce

**Comment by SUPRVISOR** [comment]
I'm dragging a jpg file into jitsi. The correspondent does not receive anything

I rename the jpg file to bmp and drag it back to jitsi. The correspondent has a message "accept"

cordially

**Comment by GNUDimarik** [comment]
Thanks!
Once I have time I check it. I think I able to do this in this or next week.
Thanks for cooperation!

**Comment by SUPRVISOR** [comment]
Thank you for your help, I did not believe it anymore.

I am french and I do not have a good english

**Comment by SUPRVISOR** [comment]
Hello

After I have another bug that lasts since very long even in the last beta, can we keep in touch and see together?

**Comment by GNUDimarik** [comment]
I'm form Russia so my english is not better too :-)
Of course. Please feel free to ping me. Use private messages if you think you need it.

**Comment by GNUDimarik** [comment]
@SUPRVISOR please check this discussion: https://github.com/jitsi/jitsi/issues/88
I'll start work in neext week.

**Comment by SUPRVISOR** [comment]
Thank you for the help

**Comment by GNUDimarik** [comment]
@ibauersachs @damencho I have some compilation errors when I working with smack4-2 branch realted with type conversions and methods overriding.
Any clues?

**Comment by GNUDimarik** [comment]
@damencho Do you understand Russian? :-)

**Comment by GNUDimarik** [comment]
@damencho Just your name is in cyrillic so it's curious :-)
Ok then I waiting for merging smack4-2 to master ...

**Comment by GNUDimarik** [comment]
Hi everyone!
I saw pull request from @damencho with changes from smack4-2.
I didn't read notifications related with certs. So quick question:
Does it mean cert issue is fixed or nearly done and once smack4-2 merged to master
Auto builds are enabled?
Sorry for typos I'm from mobile

**Comment by damencho** [comment]
The certificate issue is that the certificate on the download sit had expired.
We haven't proceeded with certs for the windows build, cause of priorities.
I will merge to master and enable builds except windows one the following days.

**Comment by GNUDimarik** [comment]
@damencho just tried to build smack4-2 branch:

$ ant make
Buildfile: D:\source\repos\jitsi\build.xml

clean-bundle-repositories:

init:

bundle-bundles:
     [copy] Copying 1 file to D:\source\repos\jitsi\sc-bundles

BUILD FAILED
D:\source\repos\jitsi\build.xml:992: Warning: Could not find file D:\source\repos\jitsi\lib\installer-exclude\jitsi-utils-1.0-20190418.111338-9.jar to copy.

Total time: 0 second

Any clues?

**Comment by damencho** [comment]
Hey, @GNUDimarik it is my fault I forgot to include those in the latest commit. Should be fine now.

**Comment by damencho** [comment]
Hey, @GNUDimarik I also just merged smack-4.2 into master.

**Comment by GNUDimarik** [comment]
Thanks @damencho Now it's fine.

**Comment by GNUDimarik** [comment]
@SUPRVISOR what OS do you use?

**Comment by GNUDimarik** [comment]
@damencho please check:

     [java] java.lang.NoClassDefFoundError: org/jitsi/utils/StringUtils
     [java]     at net.java.sip.communicator.service.contactsource.ContactDetail.<init>(ContactDetail.java:437)
     [java]     at net.java.sip.communicator.service.contactsource.ContactDetail.<init>(ContactDetail.java:364)
     [java]     at net.java.sip.communicator.impl.msghistory.MessageSourceContact.initDetails(MessageSourceContact.java:297)
     [java]     at net.java.sip.communicator.impl.msghistory.MessageSourceContact.initDetails(MessageSourceContact.java:283)
     [java]     at net.java.sip.communicator.impl.msghistory.MessageSourceService.addNewRecentMessages(MessageSourceService.java:450)
     [java]     at net.java.sip.communicator.impl.msghistory.MessageSourceService.handleProviderAddedInSeparateThread(MessageSourceService.java:518)
     [java]     at net.java.sip.communicator.impl.msghistory.MessageSourceService.access$000(MessageSourceService.java:44)
     [java]     at net.java.sip.communicator.impl.msghistory.MessageSourceService$1.run(MessageSourceService.java:478)
     [java]     at java.lang.Thread.run(Thread.java:748)
     [java] Caused by: java.lang.ClassNotFoundException: org.jitsi.utils.StringUtils not found by net.java.sip.communicator.service.contactsource [82]
     [java]     at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
     [java]     at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
     [java]     at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]     ... 9 more

**Comment by GNUDimarik** [comment]
@damencho  Seems like it's my issue .. Some libraries are not imported

**Comment by damencho** [comment]
I fixed it in commits after the merge, while running the tests.

**Comment by SUPRVISOR** [comment]
Hello

What is the relationship with my initial request? Thank you for creating another topic for the worries you meet.

I do not find it very nice to take the subject of another.

What do you think Dimitri?

Thank you

**Comment by GNUDimarik** [comment]
@damencho thanks!
It still happends:

java.lang.NoClassDefFoundError: org/jitsi/utils/StringUtils
	at net.java.sip.communicator.impl.notification.PopupMessageNotificationHandlerImpl.popupMessage(PopupMessageNotificationHandlerImpl.java:70)
	at net.java.sip.communicator.service.notification.NotificationServiceImpl.fireNotification(NotificationServiceImpl.java:251)
	at net.java.sip.communicator.service.notification.NotificationServiceImpl.fireNotification(NotificationServiceImpl.java:385)
	at net.java.sip.communicator.plugin.notificationwiring.NotificationManager.fireChatNotification(NotificationManager.java:214)
	at net.java.sip.communicator.plugin.notificationwiring.NotificationManager.messageReceived(NotificationManager.java:1295)
	at net.java.sip.communicator.service.protocol.AbstractOperationSetBasicInstantMessaging.fireMessageEvent(AbstractOperationSetBasicInstantMessaging.java:232)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicInstantMessagingJabberImpl.processMessage(OperationSetBasicInstantMessagingJabberImpl.java:965)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicInstantMessagingJabberImpl.access$900(OperationSetBasicInstantMessagingJabberImpl.java:59)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicInstantMessagingJabberImpl$SmackMessageListener.processStanza(OperationSetBasicInstantMessagingJabberImpl.java:756)
	at org.jivesoftware.smack.AbstractXMPPConnection$5.run(AbstractXMPPConnection.java:1233)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.jitsi.utils.StringUtils not found by net.java.sip.communicator.notification [22]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1988)
	at java.lang.ClassLoader.loadClass(Unknown Source)

@SUPRVISOR seems I reproduced the issue under windows.
Sorry I didn't get your previous message

**Comment by ibauersachs** [comment]
@damencho and @GNUDimarik Try to get rid of the custom StringUtils and start using Apache Commons Lang 3, no matter what the current merge issue is.

**Comment by GNUDimarik** [comment]
@damencho and @ibauersachs I'd suggest com.google.common.base.Strings.isNullOrEmpty for replacment current isNullOrEmpty and for another cases apache or something else.
Please let me know.

**Comment by damencho** [comment]
@ibauersachs @GNUDimarik I'm ok with whatever you decide, just that I'm off the following week and will not have time, probably and the week after that. 
Currently, probably there are places where it is just the import missing in some manifest files. I was debugging the xmpp tests cause they fail for that the contactlist was not cleaned. If I clean it by hand they pass.

**Comment by ibauersachs** [comment]
Why google and not Apache Commons?
And I don't have plans to work in Jitsi anytime soon.

**Comment by GNUDimarik** [comment]
@damencho and @ibauersachs I don't rememeber implementation of isNullOrEmpty in apache library but I may be wrong.
I can do this without issues :-)

**Comment by GNUDimarik** [comment]
@SUPRVISOR I meant what Operating System do you use?
Which binaries (for what Operating System?) do you need for testing once it's fixed?

**Comment by GNUDimarik** [comment]
Seems I found root cause of the current issue:

<iq to='devtest01@encryptfortress.com/jitsi-j7m8gv' id='s8Bzb-107' type='set'>
	<si
		xmlns='http://jabber.org/protocol/si' id='jsi_245709842667604492' mime-type='image/jpeg' profile='http://jabber.org/protocol/si/profile/file-transfer'>
		<file
			xmlns='http://jabber.org/protocol/si/profile/file-transfer' size='11119'
			<thumbnail
				xmlns="urn:xmpp:thumbs:0" cid="sha1+abcc9b07beb8b1190544002d0c5f371ac558843a@bob.xmpp.org" mime-type="image/png" width="64" height="64"/>
			</file>
			<feature
				xmlns="http://jabber.org/protocol/feature-neg">
				<x
					xmlns='jabber:x:data' type='form'>
					<field var='stream-method' type='list-single'>
						<option>
							<value>http://jabber.org/protocol/bytestreams</value>
						</option>
						<option>
							<value>http://jabber.org/protocol/ibb</value>
						</option>
					</field>
				</x>
			</feature>
		</si>
	</iq>

You can notice file tag is not closed before thumbnail start

**Comment by GNUDimarik** [comment]
@damencho and @ibauersachs please check related PR:
https://github.com/jitsi/jitsi-xmpp-extensions/pull/5

**Comment by GNUDimarik** [comment]
@SUPRVISOR you mentioned some additional issue. Please remind me more.
Is this jitsi bug?

**Comment by SUPRVISOR** [comment]
@GNUDimarik 
Hello i've test on Windows 7 x64, Windows 10 x64 and Linux Debian 9
Best Regards

**Comment by GNUDimarik** [comment]
@SUPRVISOR thanks for response!
Do you mean you testing this issue?
I remember you mentioned something else. No?

**Comment by GNUDimarik** [comment]
also where did you get the binaries?
@damencho @ibauersachs does jitsi provide nightly builds now?
I remember there was issue with certificates

**Comment by damencho** [comment]
Hum, the certificate problem is for windows builds, those are stopped. Now I see that we have some problem on the mac machine when building:
16:48:18     [javac] Compiling 3 source files to /Users/cruisecontrol/Documents/sipco/jitsi/classes
16:48:19     [javac] javac: invalid target release: 1.8
16:48:19     [javac] Usage: javac <options> <source files>
16:48:19     [javac] use -help for a list of possible options
16:48:19 
16:48:19 BUILD FAILED
16:48:19 /Users/cruisecontrol/Documents/sipco/jitsi/build.xml:440: Compile failed; see the compiler error output for details.

I will take a look tomorrow ...

**Comment by GNUDimarik** [comment]
Thanks for update.
So I suppose there is no place where @SUPRVISOR able to get windows binaries with fix of current issue. Right?

**Comment by damencho** [comment]
Not for the moment.

**Comment by ibauersachs** [comment]
@damencho We could just disable signing for the time being on the Windows builds... and the Mac issue is likely a JDK > 11 (or, less likely, JDK7).

**Comment by damencho** [comment]
Ok, will try that, thanks @ibauersachs

**Comment by damencho** [comment]
Latest builds are up in nightlies. I disabled mac signing (some error on executing codesign errSecInternalComponent, we had recently updated to High Sierra...), disabled windows signing. I also disabled all delta builds and macosx-no-jre... maybe we can disable more stuff in the future which is outdated and not used.

**Comment by GNUDimarik** [comment]
Great! Thanks!
Is xmpp-extension library updated? If so then issue is fixed and I suggest to close it

**Comment by SUPRVISOR** [comment]
Hello

I come back after a long time to see where we are?
I had a health concern that made me that I could not come before

**Comment by SUPRVISOR** [comment]
For the mac version

I tested the latest version on mac y'a of the best notament for the correction of the message that erased if the person wrote his message

On the other hand for the last build windows more possible to put his account XMP ca complete bug :( window that freezes and nothing more

**Comment by SUPRVISOR** [comment]
Hello

I come back after a long time to see where we are?
I had a health concern that made me that I could not come before

**Comment by GNUDimarik** [comment]
Hello.
Hope you're well now.
It should work fine now. Please check and let me know

**Comment by SUPRVISOR** [comment]
Hello

What version does it work on? because on 2.10.5550 it still does not work!

windows-> windows: KB
windows-> linux or linux-> Windows: ko

Best regards

**Comment by GNUDimarik** [comment]
Not sure which version includes the fix. Which os do you use?

**Comment by SUPRVISOR** [comment]
Hello
I have tested : 
Windows 7 x64 / Windows 10-2004 x64 / Windows 10-20H2 x64 / Linux Ubuntu 20.16 / Linux Debian 10 ....
Best regards
