### ISSUE TITLE
Debian/Ubuntu Repository: unmet dependencies

### ISSUE THREAD

**Issue by traud** [jitsi/jitsi#793]
When trying to install Jitsi Desktop, I get
```
The following packages have unmet dependencies:
 jitsi : Depends: liblibjitsi-jni (< 1.1-22-g5c9346c5-20.04~focal.1) but 1.1-23-g86401561-20.04~focal is to be installed
```

**Steps to Reproduce for Ubuntu 20.04 LTS (focal)**
```
sudo apt install libcanberra-gtk-module
sudo curl -fsSL https://nexus.ingo.ch/jitsi-desktop-unstable/jitsi-desktop-key.asc | sudo apt-key add -
echo "deb [arch=$(dpkg --print-architecture)] http://nexus.ingo.ch/jitsi-desktop-unstable $(lsb_release -cs)/" | sudo tee /etc/apt/sources.list.d/jitsi-desktop.list > /dev/null
sudo apt update
sudo apt install jitsi
```
**Steps to Reproduce for Ubuntu 22.04 LTS (jammy) or newer**
```
sudo apt install libcanberra-gtk-module
sudo wget -qO /etc/apt/keyrings/jitsi-desktop.gpg https://nexus.ingo.ch/jitsi-desktop-unstable/jitsi-desktop-key.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/jitsi-desktop.gpg] http://nexus.ingo.ch/jitsi-desktop-unstable jammy/" | sudo tee /etc/apt/sources.list.d/jitsi-desktop.list > /dev/null
sudo apt update
sudo apt install jitsi
```

**Comment by ibauersachs** [comment]
Hm, sorry about that. I need to find a better way to publish newer libjitsi versions to an APT repo. Seems the only way is to have distinct repos for each library, and then only migrate the ones referenced by Jitsi Desktop to a combined unstable and release repo.

**Comment by ibauersachs** [comment]
[r2.14.695](https://github.com/jitsi/jitsi/releases/tag/r2.14.695) should solve the immediate problem, but it'll pop up again when updating libjitsi.

**Comment by traud** [comment]
Mhm. Build 695 is a lower number than the previous 721. Was that intended?
Perhaps that is the reason, it still does not work. Anyway, it does not work either, if I go for
```
sudo apt install jisti=2.14.695.*
```
Therefore, I think the issue is something else:
APT seems to look for a ``.1`` at the end of the version string. For example, if I go for
```
apt policy *jitsi*
```
all candidates are there. Furthermore, I am able to install via
```
sudo apt install libcanberra-gtk-module libavcodec-extra
sudo apt install libjitsi-jni=2.14.695.*
sudo apt install jitsi=2.14.695.*
```
> better way to publish newer libjitsi versions to an APT repo

APT should be able to handle that, or? My current bet, I do not know for sure, it has problems to match version strings. To test my hypothesis, could you create a ``Depends`` which does not include those maximum versions with ``.1`` at the end?

**Comment by ibauersachs** [comment]
695 vs. 721: Actually, 721 shouldn't have ended up in the repo... that was a build from the branch that fixed all the installer builds. The equivalent build from branch master was 693. I need to clean the repo so that 721 disappears.

The .1 is so that patch releases could be built. The version constraint is strictly smaller than x.y.z-githash-distroDate~distroCodename**.1** and the packages are all x.y.z-githash-distroDate~distroCodename. So this _should_ work.

What's with the libcanberra-gtk-module? I haven't seen that yet. Are you using a non-Gnome Ubuntu flavor?

**Comment by traud** [comment]
> [issue] will pop up again when updating libjitsi

Seems really to work [not automatically …](https://askubuntu.com/q/1220584)

> What's with the libcanberra-gtk-module?

I am on vanilla Ubuntu 20.04 LTS. While looking at the console output, I get an warning related to that. Jitsi Desktop works without it. I am just going or it, to avoid that message. Shall I investigate it? The other package `libavcodec-extra` is to enable the audio-codec AMR-WB. But you know that.

**Comment by ibauersachs** [comment]
I guess I'll create separate Apt repositories for jitsi-lgpl-dependencies and libjitsi, similar to a ppa. Then copy the specific package version required by Jitsi into Jitsi's Apt repo. Not sure when I get to it though.
